
#
version: '2'

networks:
  procesos:
services:

  orderer.unbosque.edu.co:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.unbosque.edu.co
    container_name: orderer.unbosque.edu.co
    networks:
      - procesos

  peer0.cti.unbosque.edu.co:
    container_name: peer0.cti.unbosque.edu.co
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.cti.unbosque.edu.co
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    depends_on:
      - orderer.unbosque.edu.co
      - couchdb0
    networks:
      - procesos

  peer0.medleg.unbosque.edu.co:
    container_name: peer0.medleg.unbosque.edu.co
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.medleg.unbosque.edu.co
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    depends_on:
      - orderer.unbosque.edu.co
      - couchdb1
    networks:
      - procesos

  peer0.fiscalia.unbosque.edu.co:
    container_name: peer0.fiscalia.unbosque.edu.co
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.fiscalia.unbosque.edu.co
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    depends_on:
      - orderer.unbosque.edu.co
      - couchdb2
    networks:
      - procesos

  #CA para Medicina Legal	
  ca.medleg.unbosque.edu.co:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.medleg.unbosque.edu.co
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.medleg.unbosque.edu.co-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.medleg.unbosque.edu.co-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
      - ./crypto-config/peerOrganizations/medleg.unbosque.edu.co/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.medleg.unbosque.edu.co
    networks:
      - procesos

  #CA para Fiscalia	
  ca.fiscalia.unbosque.edu.co:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.fiscalia.unbosque.edu.co
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.fiscalia.unbosque.edu.co-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.fiscalia.unbosque.edu.co-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
    ports:
      - "7064:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
      - ./crypto-config/peerOrganizations/fiscalia.unbosque.edu.co/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.fiscalia.unbosque.edu.co
    networks:
      - procesos

  #CA para CTI	
  ca.cti.unbosque.edu.co:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.cti.unbosque.edu.co
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.cti.unbosque.edu.co-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.cti.unbosque.edu.co-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
    ports:
      - "7074:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
      - ./crypto-config/peerOrganizations/cti.unbosque.edu.co/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.cti.unbosque.edu.co
    networks:
      - procesos

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:latest
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_ID=cli
      # ---CHANGED--- peer0 from MedLeg is the default for this CLI container
      - CORE_PEER_ADDRESS=peer0.medleg.unbosque.edu.co:7051
      - CORE_PEER_LOCALMSPID=MedLegMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/medleg.unbosque.edu.co/peers/peer0.medleg.unbosque.edu.co/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/medleg.unbosque.edu.co/peers/peer0.medleg.unbosque.edu.co/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/medleg.unbosque.edu.co/peers/peer0.medleg.unbosque.edu.co/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/medleg.unbosque.edu.co/users/Admin@medleg.unbosque.edu.co/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    # ---CHANGED--- command needs to be connected out as we will be issuing commands explicitly, not using by any script
    # command: /bin/bash -c './scripts/script.sh ${CHANNEL_NAME}; sleep $TIMEOUT'
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
        - ../caliper:/opt/gopath/src/github.com/caliper
    depends_on:
      - orderer.unbosque.edu.co
      - peer0.medleg.unbosque.edu.co
      - peer0.cti.unbosque.edu.co
      - peer0.fiscalia.unbosque.edu.co
    networks:
      - procesos

  couchdb0:
    image: apache/couchdb:latest
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports: 
      - 5984:5984
    container_name: couchdb0
    networks:
      - procesos

  couchdb1:
    image: apache/couchdb:latest
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports: 
      - 5985:5984
    container_name: couchdb1
    networks:
      - procesos

  couchdb2:
    image: apache/couchdb:latest
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports: 
      - 5986:5984
    container_name: couchdb2
    networks:
      - procesos