caliper:
  blockchain: fabric
  version: "2.4"
  config:
    name: "unbosque-network"
    version: "1.0"

    clients:
      client1:
        organization: cti.unbosque.edu.co
        credentialStore:
          path: /tmp/hfc-kvs/client1
          cryptoStore:
            path: /tmp/hfc-cvs/client1

    organizations:
      cti.unbosque.edu.co:
        mspid: CtiUnbosqueMSP
        peers:
          - peer0.cti.unbosque.edu.co
        certificateAuthorities:
          - ca.cti.unbosque.edu.co

      fiscalia.unbosque.edu.co:
        mspid: FiscaliaUnbosqueMSP
        peers:
          - peer0.fiscalia.unbosque.edu.co
        certificateAuthorities:
          - ca.fiscalia.unbosque.edu.co

      medleg.unbosque.edu.co:
        mspid: MedlegUnbosqueMSP
        peers:
          - peer0.medleg.unbosque.edu.co
        certificateAuthorities:
          - ca.medleg.unbosque.edu.co

    peers:
      peer0.cti.unbosque.edu.co:
        url: grpcs://localhost:7051
        tlsCACerts:
          path: ./crypto-config/peerOrganizations/cti.unbosque.edu.co/tlsca/tlsca.cti.unbosque.edu.co-cert.pem
        grpcOptions:
          ssl-target-name-override: peer0.cti.unbosque.edu.co
          hostnameOverride: peer0.cti.unbosque.edu.co

      peer0.fiscalia.unbosque.edu.co:
        url: grpcs://localhost:8051
        tlsCACerts:
          path: ./crypto-config/peerOrganizations/fiscalia.unbosque.edu.co/tlsca/tlsca.fiscalia.unbosque.edu.co-cert.pem
        grpcOptions:
          ssl-target-name-override: peer0.fiscalia.unbosque.edu.co
          hostnameOverride: peer0.fiscalia.unbosque.edu.co

      peer0.medleg.unbosque.edu.co:
        url: grpcs://localhost:9051
        tlsCACerts:
          path: ./crypto-config/peerOrganizations/medleg.unbosque.edu.co/tlsca/tlsca.medleg.unbosque.edu.co-cert.pem
        grpcOptions:
          ssl-target-name-override: peer0.medleg.unbosque.edu.co
          hostnameOverride: peer0.medleg.unbosque.edu.co

    certificateAuthorities:
      ca.cti.unbosque.edu.co:
        url: https://localhost:7054
        caName: ca-cti-unbosque-edu-co
        tlsCACerts:
          path: ./crypto-config/peerOrganizations/cti.unbosque.edu.co/ca/ca.cti.unbosque.edu.co-cert.pem
        httpOptions:
          verify: false

      ca.fiscalia.unbosque.edu.co:
        url: https://localhost:8054
        caName: ca-fiscalia-unbosque-edu-co
        tlsCACerts:
          path: ./crypto-config/peerOrganizations/fiscalia.unbosque.edu.co/ca/ca.fiscalia.unbosque.edu.co-cert.pem
        httpOptions:
          verify: false

      ca.medleg.unbosque.edu.co:
        url: https://localhost:9054
        caName: ca-medleg-unbosque-edu-co
        tlsCACerts:
          path: ./crypto-config/peerOrganizations/medleg.unbosque.edu.co/ca/ca.medleg.unbosque.edu.co-cert.pem
        httpOptions:
          verify: false

    orderers:
      orderer.unbosque.edu.co:
        url: grpcs://localhost:7050
        tlsCACerts:
          path: ./crypto-config/ordererOrganizations/unbosque.edu.co/tlsca/tlsca.unbosque.edu.co-cert.pem
        grpcOptions:
          ssl-target-name-override: orderer.unbosque.edu.co
          hostnameOverride: orderer.unbosque.edu.co

    channels:
      mychannel:
        orderers:
          - orderer.unbosque.edu.co
        peers:
          peer0.cti.unbosque.edu.co:
            endorsingPeer: true
            chaincodeQuery: true
            ledgerQuery: true
            eventSource: true
          peer0.fiscalia.unbosque.edu.co:
            endorsingPeer: true
            chaincodeQuery: true
            ledgerQuery: true
            eventSource: true
          peer0.medleg.unbosque.edu.co:
            endorsingPeer: true
            chaincodeQuery: true
            ledgerQuery: true
            eventSource: true