#Comando de ejecucion
#cryptogen generate --config=./crypto-config.yaml

# Se crea este archivo para crear la configuración criptografica
# de la red Blockchain. Al ejecutarlo se crea la carpeta crypto-config
# con su contendio

#Orgaganizacion de tipo Orderer, la encargada de organizar las transacciones
OrdererOrgs:
    - Name: Orderer
      Domain: acme.com
      EnableNodeOUs: true
      Specs:
        - Hostname: orderer
          SANS:
            - localhost
#Organizacion de tipo Peer, 
#aqui se definen las organizaciones que participan en el canal
PeerOrgs:
    - Name: CTI
      Domain: cti.acme.com
      EnableNodeOUs: true
      Template:
        Count: 1
        SANS:
          - localhost
      Users:
        Count: 1
    - Name: MedLeg
      Domain: medleg.acme.com
      EnableNodeOUs: true
      Template:
        Count: 1
        SANS:
          - localhost
      Users:
        Count: 1
    - Name: Fiscalia
      Domain: fiscalia.acme.com
      EnableNodeOUs: true    
      Template:
        Count: 1
        SANS:
          - localhost
      Users:
        Count: 1
  